# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Reminder message

on:
  schedule:
    - cron: '0 8 * * 6' # runs every Saturday at 12AM PST
  workflow_dispatch:

jobs:
  art-team:
    runs-on: ubuntu-latest
    environment: art-team

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with: 
        ref: main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run app
      run: node app.js
      env:
        DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
        DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        NOTION_KEY: ${{ secrets.NOTION_KEY }}
        NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        NOTION_TO_DISCORD_MAP: ${{ secrets.NOTION_TO_DISCORD_MAP }}

  team-leads:

    runs-on: ubuntu-latest
    environment: team-leads

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout team-leads branch
      uses: actions/checkout@v4
      with: 
        ref: team-leads
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run app
      run: node app.js
      env:
        DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
        DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        NOTION_KEY: ${{ secrets.NOTION_KEY }}
        NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        NOTION_PAGE_ID_PROJECTS: ${{ secrets.NOTION_PAGE_ID_PROJECTS }}
        NOTION_TO_DISCORD_MAP: ${{ secrets.NOTION_TO_DISCORD_MAP }}